// AP trampoline binary — assembled at build time, embedded as a C array.
// This header is generated by CMake from ap_trampoline.S.
// If auto-generation isn't set up yet, the array is defined manually.
#pragma once
#include <stdint.h>

// The trampoline binary data and its size (defined in ap_trampoline_bin.cpp).
extern const uint8_t  g_apTrampolineData[];
extern const uint32_t g_apTrampolineSize;
