#!/usr/bin/env python3
"""
bake_font.py — Rasterize a TrueType font into a kernel-embeddable C++ glyph atlas.

Usage:
    python3 bake_font.py <font.ttf> <size_px> <output_font_atlas.cpp>

Output is a C++ source file defining brook::g_fontAtlas (a brook::FontAtlas struct)
containing a greyscale pixel atlas and per-glyph metric tables for ASCII 32-126.

The atlas is a flat uint8_t array, 8-bit greyscale coverage (0=transparent, 255=opaque).
The kernel blends each pixel using: out = fg*cov/255 + bg*(255-cov)/255.

No floating point is required in the kernel — all metrics are pre-computed here.
"""

import sys
import os
import freetype  # python-freetype / freetype-py

FIRST_CHAR  = 32    # ASCII space
LAST_CHAR   = 126   # ASCII ~
NUM_CHARS   = LAST_CHAR - FIRST_CHAR + 1
GLYPH_PAD   = 1     # pixels of padding between glyphs in atlas


def pack_glyphs(glyphs, atlas_width):
    """Pack rendered glyphs into rows, return (packed_list, atlas_height)."""
    packed = []
    cur_x = GLYPH_PAD
    cur_y = GLYPH_PAD
    row_height = 0

    for g in glyphs:
        gw = g['width']
        gh = g['height']

        if cur_x + gw + GLYPH_PAD > atlas_width:
            cur_x = GLYPH_PAD
            cur_y += row_height + GLYPH_PAD
            row_height = 0

        packed.append({**g, 'atlas_x': cur_x, 'atlas_y': cur_y})
        cur_x += gw + GLYPH_PAD
        if gh > row_height:
            row_height = gh

    atlas_height = cur_y + row_height + GLYPH_PAD

    # Round atlas height up to a multiple of 8 for alignment.
    atlas_height = (atlas_height + 7) & ~7

    return packed, atlas_height


def main():
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <font.ttf> <size_px> <output.cpp>",
              file=sys.stderr)
        sys.exit(1)

    font_path = sys.argv[1]
    size_px   = int(sys.argv[2])
    out_cpp   = sys.argv[3]

    if not os.path.exists(font_path):
        print(f"Error: font file not found: {font_path}", file=sys.stderr)
        sys.exit(1)

    # Load face and set pixel size.
    face = freetype.Face(font_path)
    face.set_pixel_sizes(0, size_px)

    # Render all printable ASCII glyphs.
    raw_glyphs = []
    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        face.load_char(
            chr(code),
            freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_NORMAL
        )
        slot   = face.glyph
        bmap   = slot.bitmap
        width  = bmap.width
        height = bmap.rows
        pitch  = abs(bmap.pitch)
        buf    = bytes(bmap.buffer)

        # Copy bitmap row by row (pitch may be padded).
        pixels = bytearray(width * height)
        for row in range(height):
            for col in range(width):
                pixels[row * width + col] = buf[row * pitch + col]

        raw_glyphs.append({
            'code':      code,
            'char':      chr(code),
            'width':     width,
            'height':    height,
            'pixels':    pixels,
            'bearing_x': slot.bitmap_left,
            'bearing_y': slot.bitmap_top,
            'advance':   slot.advance.x >> 6,
        })

    # Choose atlas width wide enough for any single glyph row.
    atlas_width = 256
    max_glyph_w = max((g['width'] for g in raw_glyphs), default=1)
    if max_glyph_w + 2 * GLYPH_PAD > atlas_width:
        atlas_width = 512

    # Pack glyphs.
    packed, atlas_height = pack_glyphs(raw_glyphs, atlas_width)

    # Compose atlas pixel array.
    atlas = bytearray(atlas_width * atlas_height)
    for g in packed:
        for row in range(g['height']):
            for col in range(g['width']):
                ax = g['atlas_x'] + col
                ay = g['atlas_y'] + row
                if ay < atlas_height and ax < atlas_width:
                    atlas[ay * atlas_width + ax] = g['pixels'][row * g['width'] + col]

    # Font-level metrics.
    metrics     = face.size
    ascent      = metrics.ascender  >> 6
    descender   = -(metrics.descender >> 6)   # positive value
    line_height = metrics.height    >> 6
    if line_height == 0:
        line_height = size_px + 2

    # Write C++ source.
    os.makedirs(os.path.dirname(out_cpp) or '.', exist_ok=True)
    with open(out_cpp, 'w') as f:
        f.write('// AUTO-GENERATED by scripts/bake_font.py — do not edit.\n')
        f.write(f'// Font: {os.path.basename(font_path)}  '
                f'Size: {size_px}px  '
                f'Glyphs: ASCII {FIRST_CHAR}-{LAST_CHAR}\n\n')
        f.write('#include "font_atlas.h"\n\n')
        f.write('namespace brook {\n\n')

        # Atlas pixel data.
        f.write(f'static const uint8_t s_atlasPixels[{len(atlas)}] = {{\n')
        for i in range(0, len(atlas), 16):
            chunk = atlas[i:i+16]
            f.write('    ' + ','.join(f'0x{b:02x}' for b in chunk) + ',\n')
        f.write('};\n\n')

        # Per-glyph info.
        f.write(f'static const GlyphInfo s_glyphs[{NUM_CHARS}] = {{\n')
        for g in packed:
            comment = repr(g['char']).replace('*/', '* /')
            f.write(
                f'    {{{g["atlas_x"]},{g["atlas_y"]},'
                f'{g["atlas_x"] + g["width"]},{g["atlas_y"] + g["height"]},'
                f'{g["bearing_x"]},{g["bearing_y"]},'
                f'{g["advance"]}}},  // {comment}\n'
            )
        f.write('};\n\n')

        # FontAtlas instance.
        f.write('const FontAtlas g_fontAtlas = {\n')
        f.write('    s_atlasPixels,\n')
        f.write(f'    {atlas_width},   // atlasWidth\n')
        f.write(f'    {atlas_height},  // atlasHeight\n')
        f.write('    s_glyphs,\n')
        f.write(f'    {NUM_CHARS},     // glyphCount\n')
        f.write(f'    {FIRST_CHAR},    // firstChar\n')
        f.write(f'    {ascent},        // ascent\n')
        f.write(f'    {descender},     // descender\n')
        f.write(f'    {line_height},   // lineHeight\n')
        f.write('};\n\n')
        f.write('} // namespace brook\n')

    total_bytes = atlas_width * atlas_height
    print(f'bake_font: {os.path.basename(font_path)} {size_px}px → '
          f'{atlas_width}×{atlas_height} atlas ({total_bytes} bytes), '
          f'{NUM_CHARS} glyphs, '
          f'ascent={ascent} descent={descender} lineHeight={line_height}')


if __name__ == '__main__':
    main()
