#!/usr/bin/env python3
"""
make_fat_image.py — creates a minimal FAT16 test image and embeds it as a C++ array.

Usage: make_fat_image.py <output.cpp> <image_size_kb>

Produces a C++ source file containing:
  extern const uint8_t  g_fatTestImage[];
  extern const uint32_t g_fatTestImageSize;

The image contains:
  BROOK.CFG  — a text config file
  TEST/       — a subdirectory
  TEST/HELLO.TXT — a text file inside the subdirectory
"""

import subprocess
import sys
import os
import tempfile

def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <output.cpp> <size_kb>", file=sys.stderr)
        sys.exit(1)

    out_cpp  = sys.argv[1]
    size_kb  = int(sys.argv[2])

    with tempfile.TemporaryDirectory() as tmpdir:
        img = os.path.join(tmpdir, "fat.img")

        # Create a FAT image using mformat.
        # -f <size_kb> specifies image size in kilobytes.
        subprocess.run(
            ["mformat", "-i", img, "-C", "-v", "BROOKVOL", "-f", str(size_kb), "::"],
            check=True, capture_output=True
        )

        # mtools config: point drive B: to our image (avoids needing /etc/mtools.conf)
        mtools_env = dict(os.environ, MTOOLS_NO_VFAT="1",
                          MTOOLSRC=os.path.join(tmpdir, "mtools.conf"))
        with open(mtools_env["MTOOLSRC"], "w") as f:
            f.write(f'drive b: file="{img}"\n')

        def mcopy(src_content: str, dst: str):
            """Write a string to the FAT image at the given path."""
            src = os.path.join(tmpdir, os.path.basename(dst.replace("/", "_")))
            with open(src, "w") as f:
                f.write(src_content)
            subprocess.run(["mcopy", "-i", img, src, "::" + dst],
                           check=True, capture_output=True, env=mtools_env)

        def mmkdir(path: str):
            subprocess.run(["mmd", "-i", img, "::" + path],
                           check=True, capture_output=True, env=mtools_env)

        mmkdir("TEST")
        mcopy("# Brook OS config\nversion=1\nserial_baud=115200\n", "BROOK.CFG")
        mcopy("Hello from the VFS!\n", "TEST/HELLO.TXT")

        with open(img, "rb") as f:
            data = f.read()

    # Emit C++ source
    size = len(data)
    with open(out_cpp, "w") as f:
        f.write("// Auto-generated by scripts/make_fat_image.py — do not edit.\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"extern const uint32_t g_fatTestImageSize = {size}u;\n\n")
        f.write("extern const uint8_t g_fatTestImage[] = {\n")
        for i in range(0, size, 16):
            chunk = data[i:i+16]
            f.write("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
        f.write("};\n")

    print(f"make_fat_image: {size_kb}KB FAT16 image → {out_cpp} ({size} bytes)")

if __name__ == "__main__":
    main()
